import type { RackBlock, RackRoom } from "@/lib/room-rack/types"

export function makeRoomRackRooms(): RackRoom[] {
  return [
    {
      id: "room-101",
      room_number: "101",
      floor: 1,
      status: "available",
      occupancy_status: "vacant",
      housekeeping_status: "clean",
      operational_status: "operational",
      room_type_id: "standard",
      room_type_name: "Standard",
      room_type_code: "STD",
      base_rate: 2400,
      max_occupancy: 2,
      notes: null,
    },
    {
      id: "room-102",
      room_number: "102",
      floor: 1,
      status: "occupied",
      occupancy_status: "occupied",
      housekeeping_status: "clean",
      operational_status: "operational",
      room_type_id: "standard",
      room_type_name: "Standard",
      room_type_code: "STD",
      base_rate: 2400,
      max_occupancy: 2,
      notes: null,
    },
    {
      id: "room-201",
      room_number: "201",
      floor: 2,
      status: "dirty",
      occupancy_status: "vacant",
      housekeeping_status: "dirty",
      operational_status: "operational",
      room_type_id: "deluxe",
      room_type_name: "Deluxe",
      room_type_code: "DLX",
      base_rate: 3900,
      max_occupancy: 3,
      notes: null,
    },
    {
      id: "room-202",
      room_number: "202",
      floor: 2,
      status: "inspected",
      occupancy_status: "vacant",
      housekeeping_status: "inspected",
      operational_status: "operational",
      room_type_id: "deluxe",
      room_type_name: "Deluxe",
      room_type_code: "DLX",
      base_rate: 3900,
      max_occupancy: 3,
      notes: "Після прибирання",
    },
    {
      id: "room-301",
      room_number: "301",
      floor: 3,
      status: "maintenance",
      occupancy_status: "vacant",
      housekeeping_status: "clean",
      operational_status: "maintenance",
      room_type_id: "suite",
      room_type_name: "Suite",
      room_type_code: "STE",
      base_rate: 5200,
      max_occupancy: 4,
      notes: "Плановий ремонт",
    },
    {
      id: "room-401",
      room_number: "401",
      floor: 4,
      status: "available",
      occupancy_status: "vacant",
      housekeeping_status: "clean",
      operational_status: "operational",
      room_type_id: "suite",
      room_type_name: "Suite",
      room_type_code: "STE",
      base_rate: 5200,
      max_occupancy: 4,
      notes: null,
    },
    {
      id: "room-999",
      room_number: "999",
      floor: 9,
      status: "out_of_order",
      occupancy_status: "vacant",
      housekeeping_status: "clean",
      operational_status: "out_of_order",
      room_type_id: "suite",
      room_type_name: "Suite",
      room_type_code: "STE",
      base_rate: 6200,
      max_occupancy: 2,
      notes: "Несправний замок",
    },
  ]
}

export function makeRoomRackBlocks(): RackBlock[] {
  return [
    {
      reservation_room_id: "rr-1",
      reservation_id: "res-1",
      reservation_number: "AUR-2026/1001",
      room_id: "room-101",
      guest: {
        id: "guest-1",
        first_name: "Anna",
        last_name: "Maria O'Connor",
        email: "anna.oconnor+vip@example.com",
        phone: "+380671234567",
        is_vip: true,
      },
      check_in: "2026-05-24",
      check_out: "2026-05-26",
      nights: 2,
      status: "pending",
      payment_status: "pending",
      total_amount: 4800,
      paid_amount: 0,
      balance: 4800,
      adults: 2,
      children: 0,
      rate: 2400,
      special_requests: "Тихий номер",
    },
    {
      reservation_room_id: "rr-2",
      reservation_id: "res-2",
      reservation_number: "AUR-2026/1002",
      room_id: "room-101",
      guest: {
        id: "guest-2",
        first_name: "Ivan",
        last_name: "Petrenko",
        email: "ivan.petrenko@example.com",
        phone: "+380501112233",
      },
      check_in: "2026-05-27",
      check_out: "2026-05-29",
      nights: 2,
      status: "confirmed",
      payment_status: "partial",
      total_amount: 4800,
      paid_amount: 2400,
      balance: 2400,
      adults: 2,
      children: 1,
      rate: 2400,
      special_requests: null,
    },
    {
      reservation_room_id: "rr-3",
      reservation_id: "res-3",
      reservation_number: "AUR-2026/1003",
      room_id: "room-102",
      guest: {
        id: "guest-3",
        first_name: "Oksana",
        last_name: "Kovalenko",
        email: "oksana.kovalenko@example.com",
        phone: "+380931234567",
      },
      check_in: "2026-05-22",
      check_out: "2026-05-25",
      nights: 3,
      status: "checked_in",
      payment_status: "paid",
      total_amount: 7200,
      paid_amount: 7200,
      balance: 0,
      adults: 2,
      children: 0,
      rate: 2400,
      special_requests: null,
    },
    {
      reservation_room_id: "rr-4",
      reservation_id: "res-4",
      reservation_number: "AUR-2026/1004",
      room_id: "room-102",
      guest: {
        id: "guest-4",
        first_name: "Serhii",
        last_name: "Bondar",
        email: "serhii.bondar@example.com",
        phone: "+380671122334",
      },
      check_in: "2026-05-18",
      check_out: "2026-05-20",
      nights: 2,
      status: "checked_out",
      payment_status: "paid",
      total_amount: 4800,
      paid_amount: 4800,
      balance: 0,
      adults: 2,
      children: 0,
      rate: 2400,
      special_requests: null,
    },
    {
      reservation_room_id: "rr-5",
      reservation_id: "res-5",
      reservation_number: "AUR-2026/1005",
      room_id: "room-201",
      guest: {
        id: "guest-5",
        first_name: "Mariya",
        last_name: "Shevchenko",
        email: "mariya.shevchenko@example.com",
        phone: "+380681234567",
      },
      check_in: "2026-05-21",
      check_out: "2026-05-23",
      nights: 2,
      status: "cancelled",
      payment_status: "refunded",
      total_amount: 7800,
      paid_amount: 7800,
      balance: 0,
      adults: 2,
      children: 1,
      rate: 3900,
      special_requests: null,
    },
    {
      reservation_room_id: "rr-6",
      reservation_id: "res-6",
      reservation_number: "AUR-2026/1006",
      room_id: "room-202",
      guest: {
        id: "guest-6",
        first_name: "Taras",
        last_name: "Hrytsenko",
        email: "taras.hrytsenko@example.com",
        phone: "+380991234567",
      },
      check_in: "2026-05-24",
      check_out: "2026-05-25",
      nights: 1,
      status: "pending",
      payment_status: "pending",
      total_amount: 3900,
      paid_amount: 0,
      balance: 3900,
      adults: 1,
      children: 0,
      rate: 3900,
      special_requests: "Ранній заїзд",
    },
    {
      reservation_room_id: "rr-7",
      reservation_id: "res-7",
      reservation_number: "AUR-2026/1007",
      room_id: "room-202",
      guest: {
        id: "guest-7",
        first_name: "Natalia",
        last_name: "Koval",
        email: "natalia.koval@example.com",
        phone: null,
      },
      check_in: "2026-05-19",
      check_out: "2026-05-21",
      nights: 2,
      status: "no_show",
      payment_status: "failed",
      total_amount: 3900,
      paid_amount: 0,
      balance: 3900,
      adults: 2,
      children: 0,
      rate: 3900,
      special_requests: null,
    },
    {
      reservation_room_id: "rr-8",
      reservation_id: "res-8",
      reservation_number: "AUR-2026/1008",
      room_id: null,
      guest: {
        id: "guest-8",
        first_name: "Unassigned",
        last_name: "Reservation",
        email: null,
        phone: null,
      },
      check_in: "2026-05-24",
      check_out: "2026-05-25",
      nights: 1,
      status: "confirmed",
      payment_status: "pending",
      total_amount: 5200,
      paid_amount: 0,
      balance: 5200,
      adults: 2,
      children: 0,
      rate: 5200,
      special_requests: null,
    },
  ]
}

export function makeRoomRackFixtures() {
  return {
    rooms: makeRoomRackRooms(),
    blocks: makeRoomRackBlocks(),
  }
}

export function makeLargeRoomRackFixtures(size = 240) {
  const roomStatuses: RackRoom["status"][] = [
    "available",
    "occupied",
    "dirty",
    "cleaning",
    "inspecting",
    "inspected",
    "maintenance",
    "blocked",
    "out_of_order",
  ]
  const reservationStatuses: RackBlock["status"][] = [
    "pending",
    "confirmed",
    "checked_in",
    "checked_out",
    "cancelled",
    "no_show",
  ]
  const roomTypes = [
    { id: "standard", name: "Standard", code: "STD", baseRate: 2400, maxOccupancy: 2 },
    { id: "deluxe", name: "Deluxe", code: "DLX", baseRate: 3900, maxOccupancy: 3 },
    { id: "suite", name: "Suite", code: "STE", baseRate: 5200, maxOccupancy: 4 },
  ]

  const rooms: RackRoom[] = []
  const blocks: RackBlock[] = []

  for (let index = 0; index < size; index += 1) {
    const number = String(100 + index).padStart(3, "0")
    const roomType = roomTypes[index % roomTypes.length]
    const roomId = `room-${number}`
    const roomStatus = roomStatuses[index % roomStatuses.length]
    rooms.push({
      id: roomId,
      room_number: number,
      floor: Math.floor(index / 20) + 1,
      status: roomStatus,
      occupancy_status: roomStatus === "occupied" ? "occupied" : "vacant",
      housekeeping_status:
        roomStatus === "dirty" ||
        roomStatus === "cleaning" ||
        roomStatus === "inspecting" ||
        roomStatus === "inspected"
          ? roomStatus
          : "clean",
      operational_status:
        roomStatus === "maintenance" ||
        roomStatus === "out_of_order" ||
        roomStatus === "blocked"
          ? roomStatus
          : "operational",
      room_type_id: roomType.id,
      room_type_name: roomType.name,
      room_type_code: roomType.code,
      base_rate: roomType.baseRate,
      max_occupancy: roomType.maxOccupancy,
      notes: null,
    })

    const reservationStatus = reservationStatuses[index % reservationStatuses.length]
    blocks.push({
      reservation_room_id: `rr-${index + 1}`,
      reservation_id: `res-${index + 1}`,
      reservation_number: `AUR-2026/${String(2000 + index)}`,
      room_id: roomId,
      guest: {
        id: `guest-${index + 1}`,
        first_name: `Guest${index + 1}`,
        last_name: `Test${index + 1}`,
        email: `guest${index + 1}@example.com`,
        phone: null,
        is_vip: index % 11 === 0,
      },
      check_in: "2026-05-24",
      check_out: "2026-05-26",
      nights: 2,
      status: reservationStatus,
      payment_status: reservationStatus === "confirmed" || reservationStatus === "checked_in" ? "paid" : "pending",
      total_amount: roomType.baseRate * 2,
      paid_amount: reservationStatus === "confirmed" || reservationStatus === "checked_in" ? roomType.baseRate * 2 : 0,
      balance: reservationStatus === "confirmed" || reservationStatus === "checked_in" ? 0 : roomType.baseRate * 2,
      adults: 2,
      children: index % 3 === 0 ? 1 : 0,
      rate: roomType.baseRate,
      special_requests: null,
    })
  }

  return { rooms, blocks }
}
